const Page = () => {
	return (
		<div className="flex flex-col gap-[20px] p-[20px]">
			<h1 className="mb-2 text-2xl font-bold">
				18 U.S.C. 2257 Exemption Statement
			</h1>
			<p className="mb-4 text-sm">Effective Date: 14 February 2025</p>

			<p>
				Pursuant to Title 18 U.S.C. § 2257 and 28 C.F.R. Part 75, all operators
				of websites that contain sexually explicit content must maintain records
				confirming that all performers appearing in such content are over the
				age of 18 at the time of production. New Verve Limited operates
				theaigo.com, an AI-based chat and content generation service. No actual
				human performers are depicted in any sexually explicit content on our
				platform. All characters, images, videos, and interactions on the
				Services are entirely computer-generated and fictional. As such, the
				content is not subject to the record-keeping requirements of 18 U.S.C. §
				2257.
			</p>

			<h2 className="mb-2 mt-4 text-xl font-bold">1. Nature of the Content</h2>
			<p>
				The Services use artificial intelligence to create fictional dialogues
				and media. No real persons are depicted in sexually explicit conduct.
				Any resemblance to real individuals, living or dead, is purely
				coincidental.
			</p>

			<h2 className="mb-2 mt-4 text-xl font-bold">2. Exemption</h2>
			<p>
				Because all sexually explicit materials on theaigo.com are generated by
				artificial intelligence and do not involve real human performers, the
				Services are exempt from the requirements of 18 U.S.C. § 2257 and
				related regulations.
			</p>

			<h2 className="mb-2 mt-4 text-xl font-bold">3. Contact Information</h2>
			<p>For questions regarding this statement, please contact:</p>
			<p>
				New Verve Limited
				<br />
				86–90 Paul Street
				<br />
				London, England, EC2A 4NE
				<br />
				Email: contact@newverve.co
			</p>
		</div>
	);
};

export default Page;
